branch-defaults:
  master:
    environment: Test-env-1
deploy:
  artifact: build/libs/hello-world-1.4.0.war
environment-defaults:
  Test-env:
    branch: null
    repository: null
  Test-env-1:
    branch: null
    repository: null
global:
  application_name: test
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Tomcat 8.5 with Java
    8 running on 64bit Amazon Linux/3.0.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
